/* Storyboard data for Tiff's 41st birthday music video, timed to "My Whole Supply".
   Shot start times (t, in seconds) come from an audio analysis of the song:
   section starts are within about ±1s, individual lines within about ±2s.
   Prompt tokens {WIFE} {HUSBAND} {CATS} {SPINDA} are expanded from the cast block. */
window.SB = {
  title: "Recalculating",
  subtitle: "A birthday music video for Tiff",
  thesis: "He’s always lost. She’s always the destination.",

  song: {
    title: "My Whole Supply",
    file: "song.mp3",
    length: 255.6,
    end: 258.6,
    bpm: 129,
    bar: 1.86,
    genre: "Electronic disco with anime-style synth leads, a male lead vocal, vocal-chop hooks and big drops",
    notes: [
      "The intro is only 3.3 seconds of vocal chops before the first line, so the film opens with a 3-second silent pre-roll on the GPS screen to give the title room.",
      "Each chorus has a stop on the beat right before “You make this oddball life lovely” (1:06, 2:09). That’s where the tableau shot freezes.",
      "After Chorus 1 (1:10–1:20) and Chorus 2 (2:13–2:19) there are instrumental vocal-chop breaks. They aren’t in the lyrics, so I’ve added dance breaks there.",
      "Verse 2’s second half works like a pre-chorus: four lines, then a ~6-second build into Chorus 2. The quiz punchline lands just before that build.",
      "The bridge builds to its loudest point on “You’re the kindest home…” (3:04), and the final chorus drops right after it.",
      "In the outro the music stops for about 2 seconds after “But being my love?”, then the biggest drop in the song lands on “You get that just right” (3:54.8). The quiet moment goes in that silence, and the film celebrates on the drop."
    ]
  },

  style: {
    gag: "Simple doodle comic style (locked look: mauve ink + accent colours): clean smooth black ink outlines of even medium weight, very simple faces with small line or dot eyes, simple expressive mouths and little blush marks, chibi proportions with big heads and small bodies, mostly white fills with flat dusty mauve-pink shading on hair and shadows, small flat muted accent colours only on key items (muted mustard yellow for Tiff's cardigan, muted teal (dark cyan) for Adrian's hoodie, cream with red spots for Spinda), no gradients, hand-drawn sparkle, sweat-drop and impact marks, exaggerated comic reactions, settings drawn simply in the same line style, thin mauve border frame",
    heart: "Simple doodle comic style (locked look: mauve ink + accent colours): clean smooth black ink outlines, very simple faces with small line or dot eyes and soft smiles, gentler and slightly less chibi proportions, mostly white fills with flat dusty mauve-pink shading plus a pale warm peach wash for lamp light or golden light, small flat muted accent colours only on key items (muted mustard yellow for Tiff's cardigan, muted teal (dark cyan) for Adrian's hoodie, cream with red spots for Spinda), no gradients, calm uncluttered composition, settings drawn simply in the same line style, thin mauve border frame",
    epic: "Simple doodle comic style (locked look: mauve ink + accent colours), dramatic version: clean black ink outlines, very simple faces, chibi proportions, white fills with dusty mauve-pink shading, bold mauve speed lines and radiating burst lines, simple spotlight cone shapes, low angle, small flat accent colours only on key items (muted mustard yellow for Tiff's cardigan, muted teal (dark cyan) for Adrian's hoodie), no gradients, thin mauve border frame",
    suffix: "16:9 frame, consistent character design, no text, no letters, no logos, no watermark, leave clean space for overlays added in edit"
  },

  cast: [
    { key: "WIFE", name: "Tiff (wife)", role: "The star. Chaotic in the moment, a genius at everything she cares about. Never the butt of a joke without also being the hero of the next shot.",
      prompt: "Tiff, a cheerful woman, [HAIR — e.g. long wavy hair], no glasses, about the same height as Adrian, cosy muted mustard yellow cardigan, striped socks with mustard stripes, phone almost always in hand with a small Spinda plush keychain hanging from it on a short strap",
      sheet: ["Default: content, cozy, glowing phone light on face", "Gag: spiral ‘Spinda eyes’ when overwhelmed (heat, quiz)", "Flex: confident, organized, clipboard energy", "Heart: soft smile, eyes half-closed", "Melting puddle variant (heat)", "Chibi turnaround"] },
    { key: "HUSBAND", name: "Adrian (husband)", role: "The exhausted-but-happy recipient of all her talents, and the singer. Deadpan by default, melts by the end.",
      prompt: "Adrian, a lanky man, short thick black hair, slightly tousled, with a soft side-swept fringe falling across his forehead and a few loose strands sticking up at the crown, round friendly face, no glasses, about the same height as Tiff, muted teal (dark cyan) hoodie, tired-but-fond eyes, deadpan expression by default",
      sheet: ["Deadpan (default)", "Composure meter: forced smile → eye twitch → steam puff", "Tiny rain cloud over head", "Sparkle eyes (food, her photos)", "Embarrassed-but-touched blush", "Versions: femboy, geek, nerd, cosplayer, card nerd"] },
    { key: "CATS", name: "The cats", role: "Miso (black tabby) and Tofu (white) are the stars; the couple has nine cats, so the other seven turn up in crowd gags. Tofu sends the final text.",
      prompt: "Miso, a chubby black tabby cat, and Tofu, a fluffy round white cat: the two stars of the couple’s nine cats, smug and extremely spoiled",
      sheet: ["Royal: crowns, velvet cushions", "Judges holding scorecards", "Party hats, unimpressed", "Holding a phone with one paw (outro)"] },
    { key: "SPINDA", name: "Spinda (plush)", role: "Tiff’s mascot and mirror. Its spiral eyes become the visual shorthand for ‘she’s lost again’.",
      prompt: "a Spinda plush matching the Spinda reference images (cream body with red spots, spiral eyes), slightly lopsided and wobbly",
      sheet: ["Locked Spinda sheet: Higgsfield job 202ed396… (turnaround, expressions, keychain, three spot patterns)", "Hero pose", "Wobble/dizzy pose", "Every Spinda has a different spot pattern"] }
  ],

  motifs: [
    { tag: "gps", name: "GPS & route line", rule: "Blue route line + arrow. Lost = loops. Planned trip = perfect line. The Bridge reveals the loops were a heart; the outro reads ‘You have arrived’, then ‘Recalculating…’." },
    { tag: "phone", name: "Phone glow & ping", rule: "One notification design and one ‘ping’ sound for the whole film, so the cat text in the outro reads instantly as the same joke." },
    { tag: "chat", name: "The group chat", rule: "Cindy, Neisa, Thei, Mel as avatar bubbles. They get every update in Verse 1 and finally show up in person at the final-chorus party." },
    { tag: "post", name: "The Post button", rule: "A tiny ‘+’ button with eyes. Begs in Verse 1, sobs in the outro, dances in the finale." },
    { tag: "sun", name: "Smug sun", rule: "The sun has a face and a grudge. Swells when she steps outside. Wears a party hat in the finale." },
    { tag: "spinda", name: "Spiral eyes", rule: "When Tiff is overwhelmed her eyes turn into Spinda spirals. Introduced at the heat gag, explained by the Spinda verse." },
    { tag: "cloud", name: "Rain cloud", rule: "Forms over Adrian at the empty dinner plate (pre-chorus). Blown away by the feast’s steam (Verse 3)." },
    { tag: "exit41", name: "Exit 41", rule: "The missed exit is numbered 41. Pays off at the cake and in the outro. The end card itself shows no number." },
    { tag: "cards", name: "Role cards", rule: "Each chorus role flips in as a trading card (‘WARDROBE EXPERT’, ‘TRAVEL PLANNER’…). Faster in Chorus 2; the final card reads ‘MY HOME’." },
    { tag: "versions", name: "Versions of Adrian", rule: "Introduced in Verse 3, merge back into one, reunite for the group photo and the finale." },
    { tag: "eyes", name: "Light in my eyes", rule: "Catchlight sparkle in Adrian’s eyes in the Verse 3 photo; returns as candlelight in the final close-up." },
    { tag: "cats", name: "Cats as witnesses", rule: "At least one cat is visible in the background of most shots, reacting." },
    { tag: "plush", name: "Plushie creep", rule: "Plushies start raining down in the first dance break, and every later wide shot has more than the last." }
  ],

  ledger: [
    { flop: "Misses the exit while catching Pokémon (Verse 1)", flex: "Plans a whole trip down to the train platform (Chorus 1, Verse 3)" },
    { flop: "Won’t post anything (Verse 1)", flex: "‘Prettiest boast’ glamour shot; best photographer he knows (Verse 1, choruses)" },
    { flop: "Melts in the sun (pre-chorus)", flex: "Turns him into a perfect cosplay in two seconds (choruses)" },
    { flop: "Cats eat before he does (pre-chorus)", flex: "Cooks a feast that blows his rain cloud away (Verse 3)" },
    { flop: "Fails the first-turn Supporter question (Verse 2)", flex: "Walks out at a big Pokémon tournament as a star (Verse 2)" },
    { flop: "Picks the phone back up for a cat (outro)", flex: "Accepts every version of him (Verse 3, final chorus)" }
  ],

  sections: [
    { key: "intro", name: "Intro", mode: "gag", chaos: 0.35, heart: 0.3,
      intent: "A 3-second silent pre-roll, then 3.3 seconds of vocal chops. Set up the GPS and its destination before the first line.",
      palette: ["#BFE3FF", "#2F6BFF", "#FFFFFF"],
      shots: [
        { id: "PR-01", t: -3, lyric: "(3 seconds of silence before the music)", size: "ECU", cam: "Locked on the dashboard GPS screen",
          action: "Silence. A stylized GPS screen in a parked car. The destination field types out ‘HOME’. A GPS voice says ‘Starting route.’ A Spinda keychain swings gently at the edge of frame.",
          act: "—", ui: "Destination: HOME", sfx: "GPS voice: “Starting route.”", trans: "Music starts; snap into IN-01 on the first chop", tags: ["gps", "spinda"], p: 1, mode: "gag",
          gen: { how: "Editor", img: "Flat cartoon GPS navigation screen inside a car dashboard, blue route line, arrow icon, a cream Spinda keychain hanging at the edge of frame", motion: "Motion graphics in the editor over a generated dashboard plate." },
          note: "Pre-roll before the song. It mirrors the ‘Recalculating…’ tag after the song ends." },
        { id: "IN-01", t: 0, lyric: "(vocal-chop intro)", size: "ECU", cam: "Snap-zoom on a dashboard GPS screen, one beat per chop",
          action: "A stylized GPS screen. Blue arrow on a route. The destination field reads ‘HOME’. A Spinda keychain swings into frame.",
          act: "—", ui: "Title in GPS font: RECALCULATING · Destination: HOME", sfx: "Soft GPS chime on the first chop", trans: "Match-cut the arrow to the real car", tags: ["gps", "spinda"], p: 2, mode: "gag",
          gen: { how: "Editor", img: "Flat cartoon GPS navigation screen inside a car dashboard, blue route line, arrow icon, a cream Spinda keychain swinging at the edge of frame", motion: "Make this as motion graphics in the editor; only the background dashboard needs generating." } },
        { id: "IN-02", t: 1.7, lyric: "(vocal-chop intro)", size: "WS", cam: "High wide, fast push toward the windshield",
          action: "A cute little car on a sunny suburban road. Two silhouettes inside, one holding a phone up high.",
          act: "—", ui: "", sfx: "", trans: "Push through the windshield into V1-01 on the first sung word", tags: ["gps"], p: 3, mode: "gag",
          gen: { how: "T2V", img: "A small rounded cartoon car driving down a sunny suburban street, blue sky, fluffy clouds, two people visible inside, passenger holding a phone up high", motion: "Car drives left to right; camera pushes quickly toward the windshield." } }
      ] },

    { key: "v1", name: "Verse 1", mode: "gag", chaos: 0.75, heart: 0.3,
      intent: "Establish the couple and the running gags fast. He needs help; she’s busy and blissful.",
      palette: ["#8FD0FF", "#3DBE7A", "#FFD23F", "#7A4FD6"],
      shots: [
        { id: "V1-01", t: 3.3, lyric: "You’re in the passenger seat, phone held high,", size: "MS two-shot", cam: "Through the windshield, locked",
          action: "Tiff in the passenger seat, phone held high above her face, totally absorbed and comfortable, feet up. Adrian driving, both hands on the wheel, eyes flicking sideways.",
          act: "Tiff: blissful. Adrian: already slightly concerned.", ui: "", sfx: "", trans: "Cut", tags: ["phone", "spinda"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Inside a small car seen through the windshield. {WIFE} in the passenger seat, holding her phone up high, absorbed and happy, feet up on the dash. {HUSBAND} driving, both hands on the wheel, glancing sideways at her with mild concern", motion: "Subtle car sway, phone screen glow flickers on her face, his eyes dart from road to her and back twice." } },
        { id: "V1-02", t: 7.0, lyric: "I’m asking, “Which turn?”—", size: "CU", cam: "Adrian’s profile, fork in the road ahead",
          action: "Adrian asks. A road fork with two blank signs looms through the windshield.",
          act: "Adrian: polite urgency.", ui: "Speech bubble: “Which turn?”", sfx: "Bubble pop", trans: "Whip-pan to phone", tags: ["gps"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Close-up of {HUSBAND} driving, turning his head toward the passenger seat, mouth open asking a question, a road fork with two signs ahead through the windshield", motion: "He turns his head and speaks; road fork approaches." } },
        { id: "V1-03", t: 8.9, lyric: "—while you’re catching pokemon", size: "OTS insert", cam: "Over Tiff’s shoulder onto her phone screen",
          action: "On the phone: a ball is flicked, lands, wobbles once, twice, three times… caught. Stars burst. Tiff does a tiny chibi fist pump.",
          act: "Tiff: total focus, then triumph. She doesn’t hear him.", ui: "Stars + ‘Gotcha!’ style burst (draw a generic ball, not real game UI)", sfx: "Three wobble clicks + sparkle", trans: "Cut", tags: ["phone"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Over-the-shoulder view of a phone screen held up in a car, a cartoon catch ball wobbling on the screen with a cute creature, {WIFE}'s thumb mid-flick", motion: "Ball wobbles three times, sparkle burst, she pumps her fist in chibi style." },
          note: "Keep the game UI stylized and generic. It reads clearly and avoids AI tools mangling real Pokémon GO screens." },
        { id: "V1-04", t: 10.85, lyric: "Then the exit slips by,", size: "MS, side window", cam: "Slow motion, sign slides past camera",
          action: "A green highway sign ‘EXIT 41’ glides past the window in slow motion. Adrian’s head turns to follow it like a sad tennis spectator.",
          act: "Adrian: silent grief. Tiff: unaware.", ui: "Sign: EXIT 41", sfx: "Slow-mo whoosh", trans: "Cut", tags: ["exit41", "gps"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Side view through a car window, a green highway exit sign gliding past, {HUSBAND} turning his head to follow it with a despairing deadpan face, {WIFE} beside him looking at her phone", motion: "Slow-motion: the sign drifts past right to left; his head rotates slowly to track it." },
          note: "‘EXIT 41’ is a birthday easter egg that pays off at the cake. Add the sign text in the edit if the model garbles it." },
        { id: "V1-05", t: 14.2, lyric: "while Cindy gets the play-by-play reply.", size: "Insert, phone", cam: "Phone fills frame; Adrian reflected in the screen",
          action: "Notification from Cindy. Tiff types at blurring speed, live-reporting the missed exit. Adrian’s deadpan face reflects in the glass.",
          act: "Tiff: gleeful narrator.", ui: "Cindy: “omg where r u now” → Tiff: “we missed the exit 😂😂 he’s doing the face”", sfx: "PING (the film’s one notification sound)", trans: "Cut to triptych on the downbeat", tags: ["phone", "chat"], p: 2, mode: "gag",
          gen: { how: "Editor", img: "Close-up of a phone screen in a car with a faint reflection of a deadpan man in the glass", motion: "Build chat bubbles as motion graphics over a generated background plate." } },
        { id: "V1-06", t: 18.6, lyric: "Neisa, Thei, Mel know every twist,", size: "Split screen ×3", cam: "Three panels pop in, one per name",
          action: "Three chat windows: Neisa gasping, Thei eating popcorn, Mel zooming in on the screen. Group chat title: ‘🚗 LIVE UPDATES’. Each panel receives the same update at once.",
          act: "Friends: invested like it’s a TV finale.", ui: "Avatars + names: Neisa · Thei · Mel", sfx: "PING ×3, one per name", trans: "Cut", tags: ["chat", "phone"], p: 2, mode: "gag",
          gen: { how: "Editor", img: "Three cute cartoon avatar reaction faces: gasping, eating popcorn, leaning in close", motion: "Avatars only; layout and bubbles in the editor." },
          note: "The singer leaves small gaps between the three names, so each panel can pop on its own name. The friends are neutral avatars, not likenesses." },
        { id: "V1-07", t: 21.8, lyric: "I’m circling the block like I planned it like this.", size: "Top-down map", cam: "Locked overhead GPS view",
          action: "The car icon loops the same block. The route line thickens with each lap. A lap counter ticks 1, 2, 3.",
          act: "—", ui: "LAP 3 · ETA: ??", sfx: "Lap beep each loop", trans: "Cut", tags: ["gps"], p: 1, mode: "gag",
          gen: { how: "Editor", img: "Top-down cartoon city block map, pastel streets, a single block highlighted", motion: "Animate the car icon and route line in the editor. You’ll reuse this exact map in the Bridge reveal." } },
        { id: "V1-08", t: 23.3, lyric: "(same line)", size: "CU", cam: "Front on Adrian, slight shake on the twitch",
          action: "Adrian’s forced, serene smile. Knuckles white. Eye twitches. Outside the window, the same corner-store cat goes past for the third time; Tiff waves at it each lap.",
          act: "Adrian: composure meter at 90%. Tiff: delighted by the cat.", ui: "", sfx: "Tiny twitch ‘tink’", trans: "Smash cut home", tags: ["cats"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Front view of {HUSBAND} driving with a tight, forced calm smile, knuckles white on the wheel, one eye twitching, a cat sitting outside a corner store visible through the window, {WIFE} waving at the cat", motion: "His eye twitches twice, the background loops past, she waves." } },
        { id: "V1-09", t: 24.7, lyric: "You’re scrolling the feed, but you won’t make a post,", size: "MS", cam: "Couch, slow push-in on the phone",
          action: "Couch at home. Tiff’s thumb scrolls a feed that rushes past like a slot machine. A tiny ‘+’ Create Post button with eyes waves at her.",
          act: "Tiff: content zombie scroll.", ui: "Feed blur; the + button with eyes", sfx: "", trans: "Cut to insert", tags: ["phone", "post"], p: 2, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} curled on a couch scrolling her phone with a relaxed blank expression, phone glow on her face, a cat asleep on her legs", motion: "Thumb scrolls fast; camera pushes slowly toward the phone." } },
        { id: "V1-10", t: 26.6, lyric: "(same line)", size: "Insert, phone", cam: "Thumb hovers, then leaves",
          action: "Her thumb hovers over the Post button. The button holds up a tiny ‘PLEASE’ sign. She… keeps scrolling. The button wilts.",
          act: "Post button: hope → heartbreak.", ui: "+ button holds sign: PLEASE", sfx: "Sad trombone (very short)", trans: "Hard cut to glamour", tags: ["post"], p: 2, mode: "gag",
          gen: { how: "Editor", img: "Close-up of a thumb hovering over a phone screen", motion: "Animate the button character in the editor so it stays on-model every time it returns." } },
        { id: "V1-11", t: 28.4, lyric: "Though my friends all agree you’re the prettiest boast.", size: "MCU glamour", cam: "Slow orbit, wind machine",
          action: "Suddenly a magazine cover: spotlight, wind-blown hair, sparkles. Hearts and like-counters from Adrian’s friends float up. In the foreground Adrian proudly shows her photo on his phone to the camera.",
          act: "Tiff: effortless star. Adrian: proud husband.", ui: "Like counters climbing; optional cover title ‘PRETTIEST BOAST’", sfx: "Camera shutter flurry", trans: "Flash-white to exterior", tags: ["phone"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "Glamorous magazine-cover style portrait of {WIFE}, studio spotlight, wind-blown hair, sparkles and floating hearts, {HUSBAND} in the foreground proudly holding up his phone showing her photo", motion: "Slow orbit around her, hair blowing, hearts float upward." } }
      ] },

    { key: "pre", name: "Pre-Chorus", mode: "gag", chaos: 0.7, heart: 0.35,
      intent: "Heat, cats, the empty plate, then a 4-second build. Use the build to give Adrian his text, so the chorus opens on a payoff.",
      palette: ["#FFE08A", "#FF9F45", "#7A4FD6", "#2B2440"],
      shots: [
        { id: "PC-01", t: 33.5, lyric: "And when the weather turns hot,", size: "WS → insert", cam: "Door opens, sun swells; insert thermometer",
          action: "Tiff steps out the front door. The sun, which has a smug face, swells to fill half the sky. A thermometer’s red line shoots up and pops the top.",
          act: "Sun: smug.", ui: "", sfx: "Rising whistle → POP", trans: "Cut", tags: ["sun"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} stepping out of a front door into blazing sunshine, an enormous cartoon sun with a smug face filling the sky, heat shimmer", motion: "The sun swells bigger; heat waves ripple." } },
        { id: "PC-02", t: 35.2, lyric: "you forget what to do,", size: "MS chibi", cam: "Locked",
          action: "Tiff freezes, eyes turn into Spinda spirals, and she melts into a happy little puddle with a face.",
          act: "Tiff: overwhelmed but cute, never miserable.", ui: "", sfx: "Melting ‘bloop’", trans: "Cut", tags: ["sun", "spinda"], p: 1, mode: "gag",
          gen: { how: "S+E", img: "START: chibi {WIFE} standing in blazing sun with dizzy spiral eyes. END: the same chibi character melted into a cute puddle with her face on top", motion: "She wobbles, eyes spiral, and melts down into a puddle." },
          note: "First appearance of the spiral eyes. They get explained in Verse 2 (‘He’s confused like me’)." },
        { id: "PC-03", t: 36.9, lyric: "One sunny afternoon and I’m navigating you.", size: "WS tracking", cam: "Side-on tracking, adventure-film map inserts",
          action: "Expedition parody: Adrian in a pith helmet with a compass leads the way. Tiff follows under a parasol with a mini fan and iced drink, holding his shirt tail. A map insert shows a dotted route hopping between shade spots.",
          act: "Adrian: finally the navigator, smug. Tiff: half-melted, trusting.", ui: "Map insert: dotted route from shade to shade", sfx: "Adventure-film sting", trans: "Iris to palace", tags: ["gps", "sun"], p: 2, mode: "gag",
          gen: { how: "I2V", img: "Side view: {HUSBAND} in a pith helmet holding a compass, confidently leading through a sun-baked street; behind him {WIFE} under a parasol with a handheld fan and an iced drink, holding his shirt tail", motion: "Both walk left to right, hopping from shadow to shadow; heat shimmer." },
          note: "Role reversal: in the car she can’t navigate; in the heat, he navigates her." },
        { id: "PC-04", t: 40.5, lyric: "The cats get the royal treatment, the softest little throne—", size: "WS", cam: "Slow tilt up a red carpet to the thrones",
          action: "Miso and Tofu on velvet thrones with crowns. The other seven cats line the red carpet as a royal court. Tiff fans the two kings with a palm leaf and serves salmon on a silver tray. A tiny chandelier.",
          act: "Cats: bored royalty. Tiff: devoted servant.", ui: "", sfx: "Harp gliss", trans: "Cut to dining room", tags: ["cats"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{CATS} sitting on tiny velvet thrones wearing crowns, a miniature red carpet and chandelier, {WIFE} kneeling and fanning them with a palm leaf while offering salmon on a silver tray", motion: "Camera tilts up the carpet to the thrones; one cat flicks its tail regally." } },
        { id: "PC-05", t: 44.4, lyric: "While I’m waiting for my dinner and text of my own.", size: "WS → CU", cam: "Long dining table, single overhead light",
          action: "Adrian alone at a long table, fork and knife upright, empty plate. He checks his phone: nothing. A tiny rain cloud forms over his head. Through the doorway behind him, the cats eat off fine china.",
          act: "Adrian: tiny, lonely, dignified.", ui: "Phone: No new messages", sfx: "Crickets; single raindrop", trans: "Hold into the build", tags: ["cloud", "phone", "cats"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{HUSBAND} sitting alone at the end of a long dining table under a single hanging lamp, empty plate, holding fork and knife upright, looking at his phone, a tiny rain cloud over his head; through a doorway behind him two cats eat from fine china", motion: "He checks his phone, sighs; the rain cloud drips once." } },
        { id: "PC-06", t: 48.3, lyric: "(4-second build into the chorus)", size: "CU → MS", cam: "Push in on the phone, then follow him to the door",
          action: "His phone finally lights up. It’s from Tiff. He stands, the rain cloud shrinks, he walks to the living-room door and grabs the handle on the last beat of the build.",
          act: "Adrian: suspicion → hope.", ui: "Tiff: “come to the living room 🎉”", sfx: "THE ping, then the build", trans: "Door flings open on the chorus drop", tags: ["phone", "cloud"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{HUSBAND} at a dining table looking at his lit-up phone with surprised hope, the small rain cloud above his head shrinking", motion: "He stands up and walks toward a closed door, reaching for the handle." },
          note: "New beat: the lyric says he’s waiting for a text, so he gets one, and it leads straight into the birthday party." }
      ] },

    { key: "c1", name: "Chorus 1", mode: "gag", chaos: 0.9, heart: 0.5,
      intent: "Fast, bright montage. Each role flips in as a trading card. This is where Tiff is the hero.",
      palette: ["#FF7AB6", "#2EC4B6", "#FFD23F", "#FFFFFF"],
      shots: [
        { id: "C1-01", t: 52.3, lyric: "Happy birthday, love, you’re my whole supply,", size: "WS", cam: "Door bursts open; confetti cannon toward camera",
          action: "The door opens onto a birthday party: banners, balloons, confetti cannon. Adrian rushes in with a gift and bear-hugs Tiff. The cats wear party hats, unimpressed.",
          act: "Both: pure joy.", ui: "", sfx: "Confetti cannon on the drop", trans: "Card flip", tags: ["cats"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Birthday party living room with banners, balloons and confetti, {HUSBAND} bursting in with a wrapped gift and hugging {WIFE}, two cats in party hats looking unimpressed", motion: "Confetti bursts toward camera, he lifts her in a hug." } },
        { id: "C1-02", t: 55.1, lyric: "My wardrobe expert, my style on the fly.", size: "MS", cam: "Locked, outfits swap on beats",
          action: "Card flips in: WARDROBE EXPERT. Tiff holds outfits up to Adrian like a paper doll: ✗, ✗… then a big ✓ and a chef’s kiss.",
          act: "Tiff: decisive stylist. Adrian: mannequin.", ui: "Role card: WARDROBE EXPERT · ✗ ✗ ✓", sfx: "Swish per outfit", trans: "Card flip", tags: ["cards"], p: 2, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} holding up different outfits against {HUSBAND} who stands like a mannequin, clothes piled around, mirror behind", motion: "Outfits swap rapidly, she rejects two then approves one with a chef’s kiss." } },
        { id: "C1-03", t: 57.9, lyric: "My makeup artist, cosplay crew,", size: "MS", cam: "F1 pit-stop framing, fast",
          action: "Card: COSPLAY CREW. Adrian sits in a chair; four clones of Tiff swarm him like an F1 pit crew: makeup, wig, costume, props. Two seconds later he stands up in full cosplay.",
          act: "Tiff ×4: focused pros. Adrian: stunned, transformed.", ui: "Role card: COSPLAY CREW · pit-stop timer 2.0s", sfx: "Air-wrench zips", trans: "Card flip", tags: ["cards", "versions"], p: 1, mode: "gag",
          gen: { how: "S+E", img: "START: {HUSBAND} in plain clothes in a chair surrounded by four copies of {WIFE} with makeup brushes, a wig, fabric and props like a pit crew. END: {HUSBAND} standing in a full Yugi Muto (Yu-Gi-Oh!) cosplay with spiky tri-colour hair and a duel disk, the four Tiffs posing proudly", motion: "Fast pit-stop blur, then he stands transformed." },
          note: "Their real cosplays: Adrian as Yugi (Yu-Gi-Oh!), Tiff as Dark Magician Girl. Reference photos go in Render Drop under ‘Ref: Cosplay’." },
        { id: "C1-04", t: 60.6, lyric: "My travel planner who gets us through.", size: "MS → WS", cam: "Pull back from desk to train platform",
          action: "Card: TRAVEL PLANNER. Tiff at a command centre of maps, train timetables and a colour-tabbed binder. Pull back: a train platform; she leads with a clipboard, perfectly on time. Adrian follows with four suitcases and a plush backpack.",
          act: "Tiff: general. Adrian: pack mule, happy.", ui: "Role card: TRAVEL PLANNER", sfx: "Station chime", trans: "Card flip", tags: ["cards", "gps", "plush"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Train platform, {WIFE} confidently leading with a clipboard and a colour-tabbed itinerary binder, {HUSBAND} behind her carrying four stacked suitcases and a backpack with a plush sticking out", motion: "They stride toward camera as the train pulls in." },
          note: "The flex that answers the car flop: she can’t read a map mid-drive, but she can plan a week to the minute." },
        { id: "C1-05", t: 63.4, lyric: "My photographer, chef—how’d I get so lucky?", size: "Two cuts", cam: "Whip-pan between them",
          action: "Card: PHOTOGRAPHER. Tiff lies on the ground for the angle, flash flash. Whip-pan. Card: CHEF. Wok flames, perfect plating. Adrian with sparkle eyes.",
          act: "Adrian: amazed.", ui: "Role cards: PHOTOGRAPHER / CHEF", sfx: "Shutter burst → sizzle", trans: "Freeze on the stop beat", tags: ["cards"], p: 2, mode: "gag",
          gen: { how: "I2V ×2", img: "A) {WIFE} lying on the floor aiming a camera up at {HUSBAND}, flash firing. B) {WIFE} cooking with wok flames in a cosy kitchen, {HUSBAND} watching with sparkling eyes", motion: "A) flash pops twice. B) flames whoosh, she plates the dish with a flourish." } },
        { id: "C1-06", t: 66.2, lyric: "You make this oddball life lovely.", size: "WS tableau", cam: "Locked, slow pull back to a framed photo on the wall",
          action: "The music stops for a beat, and the frame freezes with it. Then the living room with everything in it: cats, a few plushies, luggage, a cosplay wig on a lamp, phones, food. They laugh together on the couch. Pull back and the scene becomes a framed photo on the wall.",
          act: "Both: happy in the chaos.", ui: "", sfx: "", trans: "The photo frame shakes on the first chop", tags: ["cats", "plush", "phone"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "Cosy cluttered living room: {WIFE} and {HUSBAND} laughing together on the couch, two cats, a few Pokémon plushies, suitcases, a cosplay wig hanging on a lamp, phones and snacks on the table, warm light", motion: "Slow pull back." },
          note: "Lock this camera. Chorus 2 and the final chorus reuse this exact framing with more stuff added each time." }
      ] },

    { key: "db1", name: "Dance Break 1", mode: "gag", chaos: 0.85, heart: 0.45,
      intent: "10 seconds of vocal chops with no lyrics. Dance, and start the plushie invasion that Verse 2 is about.",
      palette: ["#FF7AB6", "#FFE3CF", "#2EC4B6", "#E0464B"],
      shots: [
        { id: "DB1-01", t: 70.1, lyric: "(instrumental: vocal chops)", size: "WS", cam: "Locked wide on the living room, cuts on the chops",
          action: "Tiff and Adrian dance badly and happily in the living room; the cats join in, sort of. On every vocal chop, a plushie drops from the ceiling: bonk, bonk, bonk.",
          act: "Both: goofy, in sync with nothing.", ui: "", sfx: "Plush ‘bonk’ on each chop", trans: "Cut", tags: ["plush", "cats"], p: 2, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} and {HUSBAND} dancing goofily in a cosy living room, two cats bouncing beside them, a few Pokémon plushies falling from the ceiling", motion: "Bouncy dance; plushies drop one at a time and bounce off the floor." } },
        { id: "DB1-02", t: 75.4, lyric: "(instrumental: vocal chops)", size: "WS → high angle", cam: "Crane up as the pile grows",
          action: "The plushie rain turns into a downpour. The pile rises to their waists, then their shoulders. The last plushie lands on Adrian’s head. Camera cranes up to show every surface covered.",
          act: "Tiff: thrilled. Adrian: drowning politely.", ui: "", sfx: "Squeaky avalanche", trans: "Match-cut to a single chair (V2-01)", tags: ["plush"], p: 2, mode: "gag",
          gen: { how: "S+E", img: "START: the couple dancing as plushies fall. END: high-angle view of the living room filled shoulder-deep with plushies, {WIFE} delighted, {HUSBAND} with a plush on his head", motion: "Plushies pour from above and fill the room." },
          note: "Not in the lyrics: this fills the instrumental break and sets up the plushie verse." }
      ] },

    { key: "v2", name: "Verse 2", mode: "gag", chaos: 1.0, heart: 0.3,
      intent: "The silliest, fastest verse. Escalate to a fake-epic tournament, then pop it with the quiz buzzer just before the build.",
      palette: ["#FFE3CF", "#E0464B", "#2B2D7A", "#FFD23F"],
      shots: [
        { id: "V2-01", t: 80.6, lyric: "Your plushies have taken every chair and shelf,", size: "4 quick cuts", cam: "Same height, cut on beats",
          action: "Adrian walks in with his (finally!) dinner plate looking for a seat: chair, plushie. Chair, plushie. Sofa, a wall of plushies. Bed, plushies tucked in under the duvet.",
          act: "Adrian: disbelief rising each cut.", ui: "", sfx: "Squeak per plush", trans: "Cut", tags: ["plush"], p: 1, mode: "gag",
          gen: { how: "I2V ×4", img: "{HUSBAND} holding a dinner plate staring at a chair occupied by a big Pokémon plushie; variants: second chair, sofa piled with plushies, bed with plushies tucked under a duvet", motion: "He approaches, stops, stares; plushie stares back." } },
        { id: "V2-02", t: 84.1, lyric: "And somehow there’s still room for someone else.", size: "MS → CU", cam: "Shelf insert, then the couch",
          action: "A tiny plushie squeezes into a packed shelf with a ‘pop’; the shelf creaks. Then Tiff, buried in plushies on the couch, pats the one free spot next to her. Adrian squeezes in. Plushies all around them.",
          act: "Tiff: welcoming. Adrian: surrenders happily.", ui: "", sfx: "Cork pop", trans: "Spotlight snap", tags: ["plush"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "{WIFE} on a couch completely surrounded by Pokémon plushies, patting the one small empty spot beside her, smiling at {HUSBAND}", motion: "She pats the spot; he squeezes in; plushies wobble." },
          note: "Both readings of ‘someone else’: one more plushie, and him. The second gives the verse a sweet beat." },
        { id: "V2-03", t: 87.6, lyric: "Spinda’s your favorite, “He’s confused like me,”", size: "Hero CU → MS", cam: "Spotlight snap, slow 180° orbit",
          action: "Hero shot of Spinda in a spotlight. Tiff hugs it. Spinda wobble-dances, spiral eyes spinning; Tiff’s eyes go spiral to match. She points at it.",
          act: "Tiff: kindred-spirit joy.", ui: "Bubble: “He gets me.”", sfx: "Wobble ‘boing’", trans: "POOF", tags: ["spinda"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{SPINDA} in a dramatic spotlight on a table, {WIFE} hugging it with sparkling eyes", motion: "The plush wobbles in a dizzy dance; her eyes turn into matching spirals; she points at it happily." },
          note: "Pays off the spiral eyes from the heat gag." },
        { id: "V2-04", t: 91.0, lyric: "And now every Spinda plushie", size: "MS", cam: "Locked on table",
          action: "One Spinda. POOF, two. POOF, three. Each has a different spot pattern.",
          act: "—", ui: "", sfx: "POOF ×2", trans: "Hard cut", tags: ["spinda", "plush"], p: 1, mode: "gag",
          gen: { how: "S+E", img: "START: one {SPINDA} on a table. END: three Spinda plushies side by side, each with a different spot pattern, puff of cartoon smoke", motion: "Two cartoon poofs, a plush appears with each." },
          note: "There is a reason for the three, but the client is keeping it back for now. No labels until we hear it." },
        { id: "V2-05", t: 93.0, lyric: "has to be three.", size: "WS", cam: "Wave crashes toward camera",
          action: "The whole room floods with Spindas. A wave knocks Adrian over. Tiff surfs the wave on a Spinda, delighted.",
          act: "Adrian: horrified. Tiff: ecstatic.", ui: "", sfx: "Wave crash of squeaks", trans: "Cut", tags: ["spinda", "plush"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "A living room flooded with hundreds of Spinda plushies like an ocean wave, {WIFE} surfing on top delighted, {HUSBAND} being swept away horrified", motion: "Plush wave crashes toward camera." } },
        { id: "V2-06", t: 94.6, lyric: "You love your Pokémon cards, but not for combat,", size: "CU", cam: "Desk lamp, macro on the card",
          action: "Tiff in white gloves with a jeweller’s loupe examines a card like a diamond. Binders, sleeves, top-loaders, perfect rows.",
          act: "Tiff: serious collector, reverent.", ui: "", sfx: "Ting of a diamond", trans: "Cut", tags: [], p: 2, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} wearing white gloves and a jeweller's loupe, inspecting a trading card under a desk lamp, neat binders and card sleeves around her", motion: "She tilts the card; it glints." } },
        { id: "V2-07", t: 98.3, lyric: "Training every week? Yeah, we don’t do that.", size: "Two-shot", cam: "Locked",
          action: "Adrian, excited, slaps a deck on a play mat: ‘Practice?’ Tiff blinks, slides the card back into its sleeve: ‘No thanks.’ A tumbleweed rolls across the mat.",
          act: "Adrian: hopeful puppy. Tiff: polite, final.", ui: "Bubbles: “Practice?” / “No thanks.”", sfx: "Tumbleweed wind", trans: "Lights slam on", tags: [], p: 2, mode: "gag",
          gen: { how: "I2V", img: "{HUSBAND} eagerly holding out a deck of cards over a play mat, {WIFE} calmly sliding a card into its sleeve, a tumbleweed rolling across the table", motion: "He offers the deck; she shakes her head; tumbleweed rolls." } },
        { id: "V2-08", t: 102.0, lyric: "You’ve played in big league, you’ve battled with the best,", size: "Low-angle WS", cam: "Slow-mo walk-out, lens flares",
          action: "A huge tournament stage. Spotlights, a roaring crowd, confetti, a giant trophy. Tiff walks out in slow motion in sunglasses and a cape, deck in hand. The jumbotron shows her face.",
          act: "Tiff: elite champion energy.", ui: "Jumbotron: TIFF · Banner: Pokémon Asia Championship Series 2025–26 · Indonesia · Master Ball League", sfx: "Crowd roar", trans: "Freeze frame", tags: ["cats"], p: 1, mode: "epic",
          gen: { how: "I2V", img: "{WIFE} walking out onto a huge card-game tournament stage in slow motion wearing sunglasses and a cape, spotlights, cheering crowd, giant trophy, confetti", motion: "Slow-motion walk toward camera, spotlights sweep, confetti falls." },
          note: "Real event: Tiff competed at the 2025–26 Pokémon Asia Championship Series, Indonesia, Master Ball League (TCG). Put that on the banner in the edit." },
        { id: "V2-09", t: 105.7, lyric: "But first-turn Supporters?", size: "Graphic", cam: "Quiz card slams in",
          action: "Freeze. A game-show question card slams into frame. Tiff slaps the buzzer with total confidence.",
          act: "Tiff: certain.", ui: "Card: “You go first. Can you play a Supporter on Turn 1?” · Tiff: “YES!”", sfx: "Slam + buzzer press", trans: "Cut", tags: ["cards"], p: 1, mode: "gag",
          gen: { how: "Editor", img: "{WIFE} slamming a big red game-show buzzer, confident grin, stage lights", motion: "Generate her buzzer slap; add the question card in the editor so the wording is exact." },
          note: "Rules check: the player who goes first can’t play a Supporter on their first turn; the player going second can. Saying ‘you go first’ keeps the quiz correct for card players watching." },
        { id: "V2-10", t: 107.6, lyric: "You still fail the test.", size: "WS", cam: "Spotlights snap off one by one",
          action: "BZZZT. A huge red ✗. Record scratch. Spotlights die. The crowd goes silent. Adrian facepalms. The cats sit at a judges’ table holding up ‘0’ scorecards. Tiff, spiral eyes, confused.",
          act: "Tiff: genuinely baffled. Adrian: disbelief.", ui: "Big red ✗ · scorecards: 0 0", sfx: "BZZZT + record scratch", trans: "Into the build", tags: ["cats", "spinda"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Darkened tournament stage with one spotlight, {WIFE} with dizzy spiral eyes and a confused face, {HUSBAND} facepalming, two cats at a judges' table holding up scorecards", motion: "Spotlights click off one by one; cats raise scorecards." },
          note: "Punchline of the verse." },
        { id: "V2-11", t: 109.5, lyric: "(6-second build into Chorus 2)", size: "MS → CU", cam: "Empty arena, slow push in",
          action: "The arena is empty. Tiff sits on the edge of the stage, still spiral-eyed. Adrian sits down beside her and hands her a Spinda. She hugs it; her eyes go back to normal. Behind them the cats flip their scorecards from ‘0’ to ‘♥’. On the last beat she grins at him.",
          act: "Tiff: baffled → comforted. Adrian: gentle.", ui: "Scorecards flip: 0 → ♥", sfx: "Build", trans: "Smash cut to Chorus 2 on the drop", tags: ["spinda", "cats"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "Empty dim tournament stage, {WIFE} sitting on the stage edge with spiral eyes, {HUSBAND} sitting beside her handing her a Spinda plush, two cats behind them holding scorecards", motion: "She hugs the plush and smiles; cats flip their cards." },
          note: "Keeps the ‘never mean’ rule: the joke lands, then he looks after her before the chorus celebrates her again." }
      ] },

    { key: "c2", name: "Chorus 2", mode: "gag", chaos: 0.95, heart: 0.5,
      intent: "Same cards, double speed, now with plushie creep. The audience knows the joke, so cut harder.",
      palette: ["#FF7AB6", "#2EC4B6", "#FFD23F", "#E0464B"],
      shots: [
        { id: "C2-01", t: 115.4, lyric: "Happy birthday, love, you’re my whole supply,", size: "WS", cam: "Same as C1-01, punchier",
          action: "Party again. Now the plushies wear party hats too, and three Spindas sit on the cake table.",
          act: "", ui: "", sfx: "", trans: "Card flip", tags: ["plush", "spinda", "cats"], p: 3, mode: "gag",
          gen: { how: "Edit", img: "Reuse the C1-01 keyframe; image-edit to add plushies in party hats and three Spinda plushies on the cake table", motion: "Same motion as C1-01." } },
        { id: "C2-02", t: 118.2, lyric: "My wardrobe expert, my style on the fly.", size: "MS", cam: "Six outfit swaps in 2 seconds",
          action: "The wardrobe card flips in twice as fast. Six outfits in two seconds, the last one ✓.", act: "", ui: "WARDROBE EXPERT", sfx: "", trans: "Card flip", tags: ["cards"], p: 3, mode: "gag",
          gen: { how: "Edit", img: "Speed-ramp the C1-02 clip and add new outfit frames", motion: "Retime in the editor." } },
        { id: "C2-03", t: 121.0, lyric: "My makeup artist, cosplay crew,", size: "MS", cam: "Pit stop at 2×",
          action: "Pit stop again, now 1.0s on the timer, and this time the crew turns on Tiff herself: she pops out as Dark Magician Girl.", act: "", ui: "COSPLAY CREW · 1.0s", sfx: "", trans: "Card flip", tags: ["cards", "versions"], p: 3, mode: "gag",
          gen: { how: "S+E", img: "As C1-03, but {WIFE} in the chair, ending in a Dark Magician Girl cosplay with the pointed hat and staff", motion: "Faster pit stop." } },
        { id: "C2-04", t: 123.7, lyric: "My travel planner who gets us through.", size: "WS", cam: "Suitcases stack higher",
          action: "Travel card. Adrian now carries six suitcases with three Spindas strapped on top.", act: "", ui: "TRAVEL PLANNER", sfx: "", trans: "Card flip", tags: ["cards", "spinda", "plush"], p: 3, mode: "gag",
          gen: { how: "Edit", img: "Edit the C1-04 keyframe: taller luggage tower with three Spinda plushies strapped on top", motion: "Same as C1-04, he wobbles." } },
        { id: "C2-05", t: 126.5, lyric: "My photographer, chef—how’d I get so lucky?", size: "Two cuts", cam: "Burst-mode flashes / plating",
          action: "Burst-mode flashes, then a dish slides into frame.", act: "", ui: "PHOTOGRAPHER / CHEF", sfx: "", trans: "Freeze on the stop beat", tags: ["cards"], p: 3, mode: "gag",
          gen: { how: "Edit", img: "Reuse C1-05 clips with new angles", motion: "Retime." } },
        { id: "C2-06", t: 129.3, lyric: "You make this oddball life lovely.", size: "WS tableau", cam: "Exactly the C1-06 framing",
          action: "The same living-room tableau after the same stop beat, but the plushies have doubled and a Spinda pile sits in the corner. Spot the difference.", act: "", ui: "", sfx: "", trans: "Into the dance break", tags: ["plush", "spinda", "cats"], p: 2, mode: "heart",
          gen: { how: "Edit", img: "Image-edit the C1-06 keyframe: double the plushies, add a Spinda pile", motion: "Same pull-back as C1-06." } }
      ] },

    { key: "db2", name: "Dance Break 2", mode: "heart", chaos: 0.55, heart: 0.65,
      intent: "6 seconds of chops. Wind the party down and turn the light gold, ready for the personal verse.",
      palette: ["#FFB86B", "#FF7AB6", "#FFE8A3", "#7A5C99"],
      shots: [
        { id: "DB2-01", t: 133.3, lyric: "(instrumental: vocal chops)", size: "MS → MCU", cam: "Slow-motion confetti, gentle push in",
          action: "Confetti settles in slow motion. The party lights fade to warm gold. Tiff and Adrian slow-dance among the plushies while the cats nap on a pile of wrapping paper.",
          act: "Both: tired, happy.", ui: "", sfx: "", trans: "Dissolve to the mirror (V3-01)", tags: ["plush", "cats"], p: 3, mode: "heart",
          gen: { how: "I2V", img: "{WIFE} and {HUSBAND} slow-dancing in a living room after a party, confetti drifting down, warm golden lamp light, cats napping on wrapping paper", motion: "Slow sway; confetti falls in slow motion." } }
      ] },

    { key: "v3", name: "Verse 3", mode: "heart", chaos: 0.5, heart: 0.75,
      intent: "Switch to heart mode: gentler proportions and a warm peach wash. Still playful, but now it’s about how she sees him. Exactly 16 bars, one line every 2 bars.",
      palette: ["#FFC98B", "#F28C6B", "#7A5C99", "#FFF3E2"],
      shots: [
        { id: "V3-01", t: 139.5, lyric: "You fix my collar, find the perfect disguise,", size: "CU in mirror", cam: "Mirror reflection, gentle push",
          action: "Her hands straighten his collar in the mirror. Quick tries: hat, glasses, wig. The final look. She steps back and gives one approving nod.",
          act: "Tiff: careful, proud. Adrian: lets her.", ui: "", sfx: "", trans: "Cut", tags: ["versions"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "Mirror reflection of {WIFE} straightening {HUSBAND}'s shirt collar, warm afternoon light, both smiling softly", motion: "She adjusts the collar, steps back and nods once." } },
        { id: "V3-02", t: 143.2, lyric: "Catch every good angle and the light in my eyes.", size: "MS orbit → photo insert", cam: "360° orbit around Adrian, then the print",
          action: "Tiff circles him with a camera, crouching, stepping, flash. Reveal the photo: he looks fantastic, a literal sparkle in his eyes. The print drops into an album.",
          act: "Adrian: a bit shy, then glowing.", ui: "", sfx: "Shutter", trans: "Cut", tags: ["eyes"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "{WIFE} crouching with a camera photographing {HUSBAND} in golden light, his eyes catching a bright sparkle", motion: "Camera orbits around him while she moves for the angle; flash." } },
        { id: "V3-03", t: 147.0, lyric: "You plan every stop, every plate, every day,", size: "WS", cam: "Scroll unrolls toward camera",
          action: "An itinerary unrolls like a royal decree across the floor and out the door: Day 1…Day 7, restaurant pins, train times, colour tabs. A map with a perfectly clean route. Adrian reads, jaw dropping.",
          act: "Adrian: awe.", ui: "Itinerary text (add in edit): Day 1 · 08:12 train · lunch ★", sfx: "Paper unroll", trans: "Cut", tags: ["gps"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "A very long hand-written travel itinerary scroll unrolling across a wooden floor and out of the front door, maps and colour tabs, {HUSBAND} holding one end with his jaw dropped", motion: "Scroll keeps unrolling past camera." },
          note: "The clean route here is the visual opposite of the Verse 1 loops." },
        { id: "V3-04", t: 150.7, lyric: "Then cook up a feast that can chase gloom away.", size: "MS", cam: "Locked, steam rises through frame",
          action: "Adrian slumps in, tired; the little rain cloud from the pre-chorus is back over his head. Tiff lifts a cloche: a huge feast. The steam rises and blows the cloud away. He lights up.",
          act: "Adrian: gloom → instant joy.", ui: "", sfx: "Cloche ‘ting’, cloud ‘poof’", trans: "Mirror flash", tags: ["cloud"], p: 1, mode: "heart",
          gen: { how: "S+E", img: "START: tired {HUSBAND} at a table with a small rain cloud over his head, {WIFE} lifting a silver cloche. END: a huge steaming bowl of Xi’an paomo (torn flatbread in rich broth) with side dishes, the cloud gone, him beaming", motion: "Steam rises and pushes the cloud away; his face brightens." },
          note: "Her signature dish: paomo, the Xi’an (Shaanxi) stew of torn flatbread in rich broth." },
        { id: "V3-05", t: 154.4, lyric: "And you never ask me to be someone new,", size: "WS", cam: "Slow dolly through a crowd of Adrians",
          action: "Adrian surrounded by many versions of himself. Tiff walks among them, unbothered, smiling at each.",
          act: "Tiff: easy acceptance.", ui: "", sfx: "", trans: "Cut on the beat", tags: ["versions"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "{HUSBAND} standing among many versions of himself in different outfits and styles, {WIFE} walking calmly between them smiling", motion: "Slow dolly forward as she walks through." } },
        { id: "V3-06", t: 158.1, lyric: "Femboy, geek, nerd, cards in my shoe—", size: "4 × ~0.9s cuts", cam: "Same framing each cut, Tiff in the same spot",
          action: "Femboy: cute outfit and hair clip, Tiff gives a thumbs up. Geek: gadgets and monitors. Nerd: glasses, books and games. Cards in shoe: a card sticks out of his sneaker; she plucks it and sleeves it.",
          act: "Tiff: the exact same loving face every time. That’s the joke.", ui: "Optional tiny labels: FEMBOY · GEEK · NERD · CARDS IN SHOE", sfx: "One beat-hit per cut", trans: "Light swirl", tags: ["versions"], p: 1, mode: "gag",
          gen: { how: "I2V ×4", img: "Four keyframes with identical framing: {HUSBAND} as a cute femboy in a skirt and hair clip; as a geek surrounded by gadgets; as a nerd with glasses and stacks of books and games; with a trading card sticking out of his sneaker; {WIFE} beside him with the same adoring smile each time", motion: "Tiny reaction per cut: thumbs up / nod / heart eyes / pluck the card." },
          note: "Decided: cute and playful (skirt, hair clip, a little blush). It must read as affectionate and celebratory." },
        { id: "V3-07", t: 161.9, lyric: "You let me be all of the things that I am,", size: "MS", cam: "Versions swirl into one, camera settles",
          action: "All the versions swirl together in light and merge back into one Adrian. Tiff takes his hand.",
          act: "Both: calm.", ui: "", sfx: "Shimmer", trans: "Cut", tags: ["versions"], p: 2, mode: "heart",
          gen: { how: "S+E", img: "START: many versions of {HUSBAND} in a circle. END: a single {HUSBAND} holding hands with {WIFE}, warm glow", motion: "Versions swirl into light and merge." } },
        { id: "V3-08", t: 165.6, lyric: "And love me completely, my favorite fan.", size: "WS → CU", cam: "Reverse of the tournament walk-out",
          action: "Adrian on a small stage (or just taking out the bins). Front row: Tiff with a huge glittery handmade sign, a foam finger, the cats with tiny pom-poms. He covers his face, embarrassed and touched.",
          act: "Tiff: loudest fan alive. Adrian: blushing.", ui: "Sign: GO ADRIAN!!! ❤️", sfx: "One-person crowd roar", trans: "Colour drains in the 1.4s gap", tags: ["cats"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "{WIFE} in the front row cheering wildly, holding a big glittery handmade sign and a foam finger, two cats beside her with tiny pom-poms; {HUSBAND} on a small stage covering his blushing face", motion: "She jumps and waves the sign; cats shake pom-poms." },
          note: "Mirrors V2-08: there she was the star, here she’s his fan." }
      ] },

    { key: "bridge", name: "Bridge", mode: "heart", chaos: 0.2, heart: 1.0,
      intent: "Quiet start, building to the loudest moment of the bridge on “home”. Strip the chaos away and land the thesis: home is her.",
      palette: ["#5B6C9E", "#A7B4D6", "#FFB86B", "#2B2440"],
      shots: [
        { id: "BR-01", t: 169.2, lyric: "So I’ll take the missed turns, the hot-day confusion,", size: "MS, in car at dusk", cam: "Slow, Polaroids drift through frame",
          action: "Polaroids of the missed exit, the loops and the melting drift slowly past. In the car at dusk, Tiff has fallen asleep in the passenger seat with her phone on her chest. Adrian glances over and smiles.",
          act: "Adrian: no frustration left.", ui: "", sfx: "", trans: "Dissolve", tags: ["exit41", "gps", "sun", "phone"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "Inside a car at dusk, {WIFE} asleep in the passenger seat with her phone resting on her chest, {HUSBAND} driving and glancing at her with a soft smile, warm streetlights", motion: "Streetlights pass slowly; he smiles." },
          note: "The shot starts in the 1.4-second gap before the line, while the colour drains." },
        { id: "BR-02", t: 175.2, lyric: "The cat-first decisions and social-media excursions.", size: "WS floor level", cam: "Locked, low",
          action: "Tiff feeds the cats first. Adrian sighs… then lies down on the floor in the cat pile. She scrolls with her head on his shoulder, and he watches the screen with her.",
          act: "Both: easy together.", ui: "", sfx: "Purring", trans: "Dissolve", tags: ["cats", "phone"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "{HUSBAND} lying on a living-room floor surrounded by cats, {WIFE} lying beside him resting her head on his shoulder scrolling her phone, both watching the screen, lamp light", motion: "A cat climbs onto his chest; she scrolls; gentle breathing." } },
        { id: "BR-03", t: 179.9, lyric: "Because underneath every joke that I make,", size: "Top-down map → zoom out", cam: "The Verse 1 map, slowly zooming out",
          action: "Stickers, bubbles and plushies peel away and fade; the colour drains to calm blue. Back to the Verse 1 GPS map. As it zooms out, the loops from ‘circling the block’ turn out to form a heart around their home.",
          act: "—", ui: "Route line forming a heart", sfx: "", trans: "Match the heart’s centre to their front door", tags: ["gps"], p: 1, mode: "heart",
          gen: { how: "Editor", img: "Reuse the V1-07 map plate at a wider zoom", motion: "Animate the route line in the editor so the heart shape is exact." },
          note: "Decided: keep the heart. It bends the lyric a little (he circled on purpose), and that’s the point of the reveal." },
        { id: "BR-04", t: 184.5, lyric: "You’re the kindest home I could ever come back to.", size: "WS → MCU", cam: "Walk up the path; reverse on the doorway",
          action: "Night. Adrian walks up the path. The door opens; warm light spills out. Tiff in the doorway, cats at her feet. The GPS pin labelled HOME drops gently above her, not the house. They hug as the music peaks.",
          act: "Both: quiet, tender. Hold it.", ui: "Map pin above Tiff: HOME", sfx: "Door creak, soft chime", trans: "Whip into the final chorus on the drop", tags: ["gps", "cats"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "Night, a cosy house, front door open with warm golden light spilling out, {WIFE} in the doorway with two cats at her feet, {HUSBAND} walking up the path toward her", motion: "He walks up; she opens her arms; they hug in the doorway." },
          note: "The emotional centre of the film. The music is building here, so the hug can be big rather than still. Add the HOME pin in the edit." }
      ] },

    { key: "final", name: "Final Chorus", mode: "heart", chaos: 0.85, heart: 0.9,
      intent: "The chorus again, bigger and golden. The group chat shows up in person. Ends on candlelight.",
      palette: ["#FFB347", "#FF7AB6", "#FFE8A3", "#7A4FD6"],
      shots: [
        { id: "FC-01", t: 189.7, lyric: "Happy birthday, love, you’re my whole supply,", size: "WS", cam: "Slow-motion confetti, crane down",
          action: "The full party: cake, presents, cats, confetti in slow motion. Cindy, Neisa, Thei and Mel are here in person, drawn as the same neutral avatar characters from the chat: the group chat, finally IRL.",
          act: "Everyone: celebration.", ui: "", sfx: "", trans: "Card flip", tags: ["chat", "cats", "plush"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "Big birthday party in a warm living room, {WIFE} in the centre, {HUSBAND} beside her, four generic cartoon friends cheering (matching the chat avatars, not real people), presents, cats in party hats, slow-motion confetti, golden light", motion: "Slow-motion confetti, camera cranes down to her." } },
        { id: "FC-02", t: 192.5, lyric: "My wardrobe expert, my style on the fly.", size: "WS runway", cam: "Runway head-on",
          action: "Fashion montage, but now they walk the runway together in coordinated outfits.", act: "", ui: "WARDROBE EXPERT", sfx: "", trans: "Card flip", tags: ["cards"], p: 2, mode: "heart",
          gen: { how: "I2V", img: "{WIFE} and {HUSBAND} walking a runway together in coordinated outfits, camera flashes", motion: "Strut toward camera, spin." } },
        { id: "FC-03", t: 195.3, lyric: "My makeup artist, cosplay crew,", size: "MS", cam: "Transformation sparkle",
          action: "Couple cosplay transformation: Adrian becomes Yugi and Tiff becomes Dark Magician Girl at the same moment, then they strike a duel pose together.", act: "", ui: "COSPLAY CREW", sfx: "", trans: "Card flip", tags: ["cards", "versions"], p: 2, mode: "heart",
          gen: { how: "S+E", img: "START: the couple in everyday clothes. END: {HUSBAND} as Yugi Muto (Yu-Gi-Oh!) and {WIFE} as Dark Magician Girl striking a duel pose together", motion: "Magical-girl-style sparkle transformation." } },
        { id: "FC-04", t: 198.0, lyric: "My travel planner who gets us through.", size: "Montage", cam: "Four fast cuts",
          action: "Four fast cuts from their real trips: the grandstand at Tokyo Racecourse, a koala at Cleland Wildlife Sanctuary, snow and penguins at Ski Dubai in Mall of the Emirates, and a train window between them. Tiff navigates on foot perfectly; Adrian does a double-take.", act: "Adrian: wait, she CAN navigate?", ui: "TRAVEL PLANNER", sfx: "", trans: "Slow down", tags: ["cards", "gps"], p: 2, mode: "heart",
          gen: { how: "I2V ×4", img: "Travel snapshots of {WIFE} and {HUSBAND}: train window seats, rolling luggage through a station, reading a paper map, cheering at the grandstand of Tokyo Racecourse, meeting a koala at Cleland Wildlife Sanctuary, waving at penguins in the indoor snow of Ski Dubai", motion: "Short movement per cut." } },
        { id: "FC-05", t: 200.8, lyric: "My photographer, chef—my best friend, my home,", size: "Montage, slower", cam: "Softer cuts",
          action: "She photographs him… then he takes the camera and photographs her for once. Cooking together, flour on noses. Laughing on the couch, cats on laps.",
          act: "Both: ordinary, perfect.", ui: "Final role card: MY HOME", sfx: "", trans: "Cut", tags: ["cards", "cats"], p: 1, mode: "heart",
          gen: { how: "I2V ×3", img: "A) {HUSBAND} holding the camera photographing {WIFE}, who laughs. B) the couple cooking together with flour on their noses. C) the couple cuddling on the couch with cats on their laps", motion: "Gentle, slower movements." } },
        { id: "FC-06", t: 203.6, lyric: "You make every version of me feel known.", size: "WS group photo", cam: "Camera on self-timer, flash, freeze",
          action: "Every version of Adrian (everyday, femboy, geek, nerd, cosplayer, card nerd) gathers for a group photo with Tiff in the middle. Three Spindas with different spots sit in front. Self-timer, flash, freeze frame.",
          act: "Tiff: knows every one of them.", ui: "Role card: EVERY VERSION · ACCEPTED", sfx: "Timer beeps → flash", trans: "Flash to cake", tags: ["versions", "spinda"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "Group photo: {WIFE} in the middle surrounded by six versions of {HUSBAND} (everyday, femboy, geek, nerd, cosplayer, card collector), three Spinda plushies with different spot patterns sitting in front, warm light", motion: "Everyone leans in; flash; freeze." } },
        { id: "FC-07", t: 207.0, lyric: "Here’s to your forty-first—just a playful disguise,", size: "MS", cam: "Locked",
          action: "Adrian proudly presents a cake with ‘41’ candles, looks at camera, then slaps his hand over the numbers and whistles innocently.",
          act: "Adrian: proud → cheeky.", ui: "Candles: 41", sfx: "Whistle", trans: "Cut", tags: ["exit41"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{HUSBAND} proudly holding a birthday cake with lit number candles, {WIFE} beside him, warm party light", motion: "He lifts the cake, glances at camera, covers the candles with his hand." } },
        { id: "FC-08", t: 211.3, lyric: "No numbers disclosed, just the love in my eyes.", size: "ECU → reverse ECU", cam: "Very slow push",
          action: "Close-up on Adrian’s eyes, candlelight in them (callback to V3-02). Reverse: Tiff’s face in candlelight, making a wish. She blows; the candles go out as the music dips.",
          act: "Both: genuine.", ui: "", sfx: "", trans: "Black for a breath in the dip, then the outro", tags: ["eyes"], p: 1, mode: "heart",
          gen: { how: "I2V ×2", img: "A) extreme close-up of {HUSBAND}'s eyes reflecting warm candlelight, full of love. B) {WIFE}'s face lit by birthday candles, eyes closed, making a wish", motion: "Very slow push-in; candle flicker; she blows the candles out." } }
      ] },

    { key: "outro", name: "Outro", mode: "gag", chaos: 0.6, heart: 0.95,
      intent: "Callbacks in the breakdown, a 2-second silence for the sincere moment, then the biggest drop of the song for the finale.",
      palette: ["#2B2440", "#FFB86B", "#2F6BFF", "#FF7AB6"],
      shots: [
        { id: "OU-01", t: 217.0, lyric: "Now put down the phone—", size: "Two-shot couch", cam: "Locked",
          action: "Adrian, gently: ‘Put down the phone.’ Tiff sets it face-down in slow motion, like parting with a loved one.",
          act: "Tiff: theatrical sacrifice.", ui: "Bubble: “Put down the phone.”", sfx: "", trans: "Cut", tags: ["phone"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} and {HUSBAND} on the couch at night, she slowly places her phone face-down on the coffee table with a dramatic sad face", motion: "Slow-motion phone placement." } },
        { id: "OU-02", t: 219.6, lyric: "—unless the cats text first.", size: "Insert → WS", cam: "Insert on phone, pull back to reveal the cat",
          action: "PING. The notification is from the cat. Tiff snatches the phone instantly. Reveal: Tofu, the white cat, at the other end of the couch with a paw on Adrian’s phone. Adrian stares at Tofu. Tofu stares back. He gives up and flops.",
          act: "Cat: innocent. Adrian: defeated.", ui: "Notification from Tofu: “where is my dinner”", sfx: "THE ping", trans: "Cut", tags: ["phone", "cats"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "A smug cat sitting on the end of a couch with one paw on a phone, {HUSBAND} staring at it in disbelief, {WIFE} grabbing her phone", motion: "Cat blinks slowly; he flops back onto the couch." } },
        { id: "OU-03", t: 223.3, lyric: "I love you, darling. You’re the best and the worst", size: "MS hug", cam: "Locked",
          action: "Adrian hugs her. Labels pop above her: BEST ❤️ and WORST 😂. Optional: her role card flips over to show a stats back: Weakness: Directions ×2 · Heat ×2.",
          act: "Both: laughing.", ui: "BEST ❤️ / WORST 😂", sfx: "Two pops", trans: "Fast cuts", tags: ["cards"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{HUSBAND} hugging {WIFE} from the side on the couch, both laughing", motion: "Hug and laugh." } },
        { id: "OU-04", t: 227.6, lyric: "At directions, at heat, at posting online—", size: "3 × ~1.4s cuts", cam: "Reused shots",
          action: "Three rapid callbacks: EXIT 41 whooshing past; the puddle under a smug sun; the Post button sobbing into a tiny handkerchief.",
          act: "", ui: "", sfx: "Whoosh / bloop / sob", trans: "Hard stop", tags: ["exit41", "sun", "post", "gps"], p: 1, mode: "gag",
          gen: { how: "Edit", img: "Re-cut V1-04, PC-02, V1-10", motion: "New Post-button sob animation in the editor." } },
        { id: "OU-05", t: 232.0, lyric: "But being my love? (2s of near-silence)", size: "WS, still", cam: "Locked. Nothing moves except the cats",
          action: "Evening on the couch. The cats curl up. They hold hands. On the coffee table, the phone’s GPS quietly reads ‘You have arrived’. Hold through the silence.",
          act: "Both: peaceful.", ui: "Phone: You have arrived", sfx: "", trans: "Everything bursts on the drop", tags: ["gps", "cats", "phone"], p: 1, mode: "heart",
          gen: { how: "I2V", img: "Quiet evening living room, warm lamp light, {WIFE} and {HUSBAND} on the couch holding hands, two cats curled up beside them, a phone on the coffee table glowing softly", motion: "Almost still: cats breathe, a tail flicks, lamp glow." },
          note: "This is the brief’s quiet ending, placed in the silence the song gives us." },
        { id: "OU-06", t: 234.8, lyric: "You get that just right. (final drop)", size: "WS → crane up", cam: "Pull back and up as the room fills",
          action: "On the drop, the whole film comes back to celebrate around them: the cats in crowns, the avatar friends, the versions of Adrian, a wave of Spindas, the smug sun in a party hat, the Post button dancing. Tiff and Adrian stay in the middle, still holding hands.",
          act: "Everyone: joy. The couple: just looking at each other.", ui: "", sfx: "", trans: "Confetti wipe to the end card", tags: ["cats", "chat", "versions", "spinda", "sun", "post", "plush"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "Joyful finale party in a living room: {WIFE} and {HUSBAND} holding hands in the centre, surrounded by cats wearing crowns, four generic cartoon friends cheering, several versions of Adrian dancing, a wave of Spinda plushies, a cartoon sun with a party hat in the window, confetti everywhere", motion: "Camera pulls back and rises as everyone dances around the still couple." },
          note: "Decided: the quiet moment lives in the 2-second stop (OU-05), and the film celebrates on the drop." },
        { id: "OU-07", t: 244.4, lyric: "(vocal-chop tail)", size: "Title card", cam: "—",
          action: "End card over the closing chops: Happy Birthday, My Love ❤️. No number, in keeping with ‘No numbers disclosed’. A tiny Spinda wobbles across under the text.",
          act: "", ui: "Happy Birthday, My Love ❤️", sfx: "", trans: "Hold to the end of the song (4:15.6)", tags: ["spinda"], p: 1, mode: "heart",
          gen: { how: "Editor", img: "Build in the editor.", motion: "—" },
          note: "Decided: no number on the end card. The 41 only appears on EXIT 41 and the cake candles." },
        { id: "OU-08", t: 255.6, lyric: "(after the music ends)", size: "MCU", cam: "Locked, then cut to black",
          action: "Silence. Tiff picks the phone up. The GPS voice: ‘Recalculating…’. She looks at Adrian, guilty. Cut to black.",
          act: "Tiff: caught. Adrian: resigned love.", ui: "GPS: Recalculating…", sfx: "GPS voice line", trans: "Cut to black", tags: ["gps", "phone"], p: 1, mode: "gag",
          gen: { how: "I2V", img: "{WIFE} on the couch holding her phone, looking sideways at {HUSBAND} with a guilty grin, warm lamp light", motion: "She slowly turns her eyes to him; hold." },
          note: "A 3-second tag after the song. Use the same GPS voice as the pre-roll: record it, or generate it with a text-to-speech voice." }
      ] }
  ],

  production: {
    minAnimSeconds: 3,
    animatePriorityShort: true,
    rule: "Only shots that stay on screen for 3 seconds or more get animated, plus every priority-scene shot (exception approved 7 October). Other shorter shots are stills with an editor move such as a push-in, shake or pop. Editor shots are built in the edit.",
    priorities: [
      { n: 1, scene: "Missing the exit while catching Pokémon", shots: ["V1-02", "V1-03", "V1-04"] },
      { n: 2, scene: "Circling the block", shots: ["V1-07", "V1-08"] },
      { n: 3, scene: "Wife melting in the heat", shots: ["PC-01", "PC-02"] },
      { n: 4, scene: "Cats get a royal throne while husband waits for dinner", shots: ["PC-04", "PC-05"] },
      { n: 5, scene: "House completely invaded by plushies", shots: ["DB1-01", "DB1-02", "V2-01", "V2-02"] },
      { n: 6, scene: "Spinda multiplying 1 → 3 → ridiculous numbers", shots: ["V2-04", "V2-05"] },
      { n: 7, scene: "Tournament → failing the first-turn Supporter question", shots: ["V2-08", "V2-09", "V2-10"] },
      { n: 8, scene: "The versions of Adrian accepted by Tiff", shots: ["V3-05", "V3-06", "V3-07"] },
      { n: 9, scene: "Emotional ‘you’re my home’ bridge", shots: ["BR-03", "BR-04"] },
      { n: 10, scene: "Cat texts → wife picks the phone up again", shots: ["OU-01", "OU-02"] },
      { n: 11, scene: "Final ‘being my love? You get that just right.’", shots: ["OU-05", "OU-06"] }
    ]
  },

  decisions: [
    { q: "Names", a: "Tiff and Adrian, as in the brief." },
    { q: "Format", a: "16:9 landscape." },
    { q: "Style", a: "Locked: simple doodle comic, mauve ink (black line, white fills, dusty mauve-pink shading) plus small accent colours: mustard for Tiff, teal (dark cyan) for Adrian, cream and red for Spinda (colours changed 8 October). Reference shot: the fixed V1-01 car swatch." },
    { q: "Ending", a: "Quiet moment in the 2-second stop, then the whole cast celebrates on the final drop." },
    { q: "Dance breaks", a: "Keep both: plushie-rain dance (1:10) and slow dance (2:13)." },
    { q: "Pre-roll", a: "3 seconds of silence on the GPS screen before the music, mirroring the ‘Recalculating…’ tag." },
    { q: "End card", a: "‘Happy Birthday, My Love ❤️’ with no number. The 41 lives on the exit sign and the cake." },
    { q: "Heart route", a: "Keep the reveal: the Verse 1 loops form a heart around their home." },
    { q: "Friends", a: "Neutral cartoon avatars with name labels, everywhere they appear." },
    { q: "Audience", a: "Private gift, so Pokémon and Spinda stay front and centre." },
    { q: "‘Someone else’", a: "Both readings: one more plushie, then Tiff makes room for Adrian." },
    { q: "References", a: "Photos of Tiff, Adrian, the cats and the real Spinda plush will drive the character sheets." },
    { q: "Client sign-off", a: "Adrian approved the doodle style (mauve ink + accents) on 7 October." },
    { q: "Deadline", a: "Finished video needed by 20 October." },
    { q: "Video model", a: "Kling 3.0 (std, sound off): the car-shot test held the doodle style." },
    { q: "Short priority jokes", a: "Animate them anyway, as 3-second clips trimmed to the beat." },
    { q: "Tiff and Adrian designs", a: "Wait for the client’s photos before the character sheets. No glasses on either; about the same height." },
    { q: "Names on screen", a: "Tiff and Adrian." },
    { q: "Femboy look", a: "Cute and playful." },
    { q: "Cats", a: "Nine cats; Miso (black tabby) and Tofu (white) are the stars. Tofu sends the final text." },
    { q: "Cosplay", a: "Adrian as Yugi (Yu-Gi-Oh!), Tiff as Dark Magician Girl." },
    { q: "Travel", a: "Tokyo Racecourse, Cleland Wildlife Sanctuary, Ski Dubai (Mall of the Emirates)." },
    { q: "Feast", a: "Paomo, the Xi’an stew." },
    { q: "Tournament", a: "2025–26 Pokémon Asia Championship Series, Indonesia, Master Ball League (TCG)." },
    { q: "Nothing to avoid", a: "No features are off-limits for the gags." }
  ],

  clientQuestions: [
    { q: "Photos of Tiff", why: "Adrian’s photos are in (8 October). For Tiff, 3–5: a straight-on face, a 3/4 angle, one full-body and one natural smile. Daylight, no filters, one person per photo, JPG." },
    { q: "Photos of Miso and Tofu", why: "2–3 each (face, side, full body) so the markings come out right." },
    { q: "Tiff’s real Spinda plush", why: "2–3 photos, front and side." },
    { q: "Cosplay photos", why: "Any photos of Adrian as Yugi and Tiff as Dark Magician Girl." },
    { q: "Travel photos", why: "Photos from Tokyo Racecourse, Cleland Wildlife Sanctuary and Ski Dubai." },
    { q: "Three Spindas", why: "The real reason every Spinda comes in threes, whenever they’re ready to share it." }
  ],


  peaks: [0.028, 0.12, 0.217, 0.245, 0.377, 0.391, 0.315, 0.266, 0.322, 0.344, 0.299, 0.278, 0.315, 0.344, 0.325, 0.305, 0.268, 0.271, 0.287, 0.394, 0.371, 0.493, 0.323, 0.227, 0.246, 0.299, 0.438, 0.634, 0.544, 0.602, 0.516, 0.625, 0.53, 0.605, 0.514, 0.62, 0.527, 0.623, 0.523, 0.605, 0.528, 0.599, 0.525, 0.609, 0.503, 0.59, 0.488, 0.595, 0.455, 0.32, 0.337, 0.405, 0.353, 0.36, 0.354, 0.336, 0.348, 0.35, 0.445, 0.379, 0.432, 0.45, 0.478, 0.446, 0.47, 0.4, 0.5, 0.514, 0.523, 0.523, 0.5, 0.448, 0.635, 0.611, 0.675, 0.565, 0.679, 0.607, 0.638, 0.624, 0.623, 0.648, 0.631, 0.651, 0.593, 0.655, 0.574, 0.706, 0.595, 0.717, 0.6, 0.593, 0.563, 0.454, 0.315, 0.375, 0.46, 0.518, 0.668, 0.683, 0.725, 0.649, 0.672, 0.604, 0.675, 0.612, 0.701, 0.635, 0.676, 0.601, 0.694, 0.624, 0.665, 0.616, 0.648, 0.658, 0.561, 0.531, 0.477, 0.639, 0.572, 0.658, 0.583, 0.639, 0.598, 0.724, 0.584, 0.669, 0.586, 0.683, 0.579, 0.675, 0.668, 0.646, 0.636, 0.606, 0.661, 0.602, 0.707, 0.627, 0.691, 0.623, 0.691, 0.597, 0.68, 0.61, 0.689, 0.604, 0.654, 0.649, 0.618, 0.647, 0.618, 0.665, 0.57, 0.626, 0.571, 0.649, 0.552, 0.532, 0.488, 0.666, 0.612, 0.745, 0.663, 0.743, 0.662, 0.626, 0.649, 0.636, 0.688, 0.63, 0.675, 0.603, 0.695, 0.6, 0.7, 0.573, 0.707, 0.659, 0.623, 0.638, 0.454, 0.248, 0.341, 0.422, 0.671, 0.715, 0.642, 0.729, 0.648, 0.704, 0.641, 0.702, 0.612, 0.682, 0.662, 0.646, 0.346, 0.285, 0.564, 0.714, 0.506, 0.446, 0.339, 0.503, 0.684, 0.577, 0.689, 0.629, 0.672, 0.634, 0.675, 0.661, 0.616, 0.65, 0.649, 0.675, 0.619, 0.658, 0.634, 0.68, 0.649, 0.693, 0.643, 0.682, 0.662, 0.671, 0.703, 0.549, 0.491, 0.607, 0.517, 0.342, 0.476, 0.266, 0.4, 0.315, 0.249, 0.358, 0.502, 0.572, 0.485, 0.381, 0.366, 0.322, 0.36, 0.369, 0.401, 0.461, 0.453, 0.447, 0.536, 0.658, 0.696, 0.638, 0.708, 0.649, 0.732, 0.74, 0.749, 0.811, 0.867, 0.819, 0.793, 0.742, 0.559, 0.481, 0.601, 0.498, 0.568, 0.625, 0.468, 0.411, 0.442, 0.654, 0.663, 0.454, 0.43, 0.637, 0.562, 0.8, 0.575, 0.711, 0.79, 0.779, 0.751, 0.783, 0.816, 0.754, 0.842, 0.791, 0.851, 0.802, 0.828, 0.768, 0.857, 0.788, 0.85, 0.825, 0.635, 0.584, 0.394, 0.287, 0.183, 0.285, 0.257, 0.356, 0.675, 0.655, 0.701, 0.646, 0.718, 0.699, 0.679, 0.744, 0.722, 0.737, 0.7, 0.645, 0.492, 0.682, 0.79, 0.526, 0.408, 0.271, 0.183, 0.663, 0.321, 0.524, 0.537, 0.27, 0.854, 1.0, 0.923, 0.998, 0.948, 0.99, 0.928, 0.937, 0.937, 0.91, 0.968, 0.921, 0.95, 0.964, 0.973, 0.893, 0.928, 0.675, 0.658, 0.574, 0.566, 0.696, 0.896, 0.913, 0.769, 0.58, 0.097, 0.014]
};
